import { Router } from "express";
import userController from "../controller/user.controller";
const router = Router();
import { authMiddleware } from "../middlewares/auth.middlewate";
router.get("/contacts", authMiddleware, userController.getContacts);
router.post("/create-contact", authMiddleware, userController.createContact);
router.post("/send-otp", authMiddleware, userController.sendOtp);
router.put("/profile", authMiddleware, userController.updateProfile);
router.put("/email", authMiddleware, userController.updateEmail);
router.delete("/delete", authMiddleware, userController.deleteUser);
export default router;
